version: 2
jobs:
  build:

    working_directory: ~/reddit-ui-test

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: reddit-ui-test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: reddit-ui-test-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: ./target/surefire-reports/emailable-report.html

      - store_artifacts:
          path: ./target/surefire-reports/Reddit-Ui-Test.html